# -*- coding: utf-8 -*-
"""Multilingual sentiment test — MarianMT en-OTHER Model with sentiment-based modification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtcf7-W5HGytdKksk2AHW8AsFV8BF4vO
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers --upgrade
# !pip install mosestokenizer

"""### Translating with Transformers
Thanks to everyone who helped with this, especially: 


*   [Jörg Tiedemann](https://researchportal.helsinki.fi/en/persons/j%C3%B6rg-tiedemann) from the [OPUS project](http://opus.nlpl.eu/)
*  [Marcin Junczys-Dowmunt](https://twitter.com/marian_nmt) from Microsoft's [Marian NMT](https://t.co/IuL994N6nQ?amp=1) library
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# from transformers import MarianMTModel, MarianTokenizer
# src_text = [
#     '>>fr<< This is a sentence in english that we want to translate to french.',
#     '>>pt<< This should go to portuguese.',
#     '>>es<< And this to Spanish.'
# ]
# 
# romance_model_name = 'Helsinki-NLP/opus-mt-en-ROMANCE'
# romance_tokenizer = MarianTokenizer.from_pretrained(romance_model_name)
# # see tokenizer.supported_language_codes for choices
# romance_model = MarianMTModel.from_pretrained(romance_model_name)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# indonesian_model_name = 'Helsinki-NLP/opus-mt-en-id'
# indonesian_tokenizer = MarianTokenizer.from_pretrained(indonesian_model_name)
# # see tokenizer.supported_language_codes for choices
# indonesian_model = MarianMTModel.from_pretrained(indonesian_model_name)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# slavic_model_name = 'Helsinki-NLP/opus-mt-en-sla'
# slavic_tokenizer = MarianTokenizer.from_pretrained(slavic_model_name)
# # see tokenizer.supported_language_codes for choices
# slavic_model = MarianMTModel.from_pretrained(slavic_model_name)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# german_model_name = 'Helsinki-NLP/opus-mt-en-de'
# german_tokenizer = MarianTokenizer.from_pretrained(german_model_name)
# # see tokenizer.supported_language_codes for choices
# german_model = MarianMTModel.from_pretrained(german_model_name)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# finnish_model_name = 'Helsinki-NLP/opus-mt-en-fi'
# finnish_tokenizer = MarianTokenizer.from_pretrained(finnish_model_name)
# # see tokenizer.supported_language_codes for choices
# finnish_model = MarianMTModel.from_pretrained(finnish_model_name)

#@title Translate with Transformers
english_text = "Time Warner Road Runner customer support here absolutely blows." #@param {type:"string"}
tgt_language = "id" #@param ["fr", "es", "it", "pt", "pt_br", "ro", "ca", "gl", "pt_BR", "la", "wa", "fur", "oc", "fr_CA", "sc", "es_ES", "es_MX", "es_AR", "es_PR", "es_UY", "es_CL", "es_CO", "es_CR", "es_GT", "es_HN", "es_NI", "es_PA", "es_PE", "es_VE", "es_DO", "es_EC", "es_SV", "an", "pt_PT", "frp", "lad", "vec", "fr_FR", "co", "it_IT", "lld", "lij", "lmo", "nap", "rm", "scn", "mwl"] {allow-input: true}

src_txt = f'>>{tgt_language}<< {english_text}'
translated = indonesian_model.generate(**indonesian_tokenizer.prepare_seq2seq_batch([src_txt]), num_beams=10, num_return_sequences=10)
print([indonesian_tokenizer.decode(t, skip_special_tokens=True) for t in translated])

import torch
from google.colab import drive
drive.mount("/content/drive")

!pip install transformers

from transformers import XLMRobertaForSequenceClassification, AdamW, BertConfig

# Load BertForSequenceClassification, the pretrained BERT model with a single 
# linear classification layer on top. 

# sentiment_model = XLMRobertaForSequenceClassification.from_pretrained(
#     "xlm-roberta-base", # Use the large XLM Roberta model.
#     num_labels = 2, # The number of output labels--2 for binary classification, 3 for ternary, etc.
#                     # You can increase this for multi-class tasks.   
#     output_attentions = False, # Whether the model returns attentions weights.
#     output_hidden_states = False, # Whether the model returns all hidden-states.
# )

model_state_dict = torch.load("/content/drive/My Drive/Summer Project 2020/XLM_R_ML_sentiment_model.pt", map_location=torch.device('cpu'))
sentiment_model = XLMRobertaForSequenceClassification.from_pretrained("xlm-roberta-base", # Use the large XLM Roberta model.
    num_labels = 2, # The number of output labels--2 for binary classification, 3 for ternary, etc.
                    # You can increase this for multi-class tasks.   
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
    state_dict=model_state_dict
)
# sentiment_model.to('cpu')

# sentiment_model.load_state_dict(torch.load("/content/drive/My Drive/Summer Project 2020/XLM_R_ML_sentiment_model.pt", map_location=torch.device('cpu')))

sentiment_model.eval()

from transformers import BertTokenizer, XLMRobertaTokenizer
from torch.utils.data import TensorDataset, DataLoader
import numpy as np
import re
from bs4 import BeautifulSoup

# gets the tweet into the format we want
def clean_tweet(tweet):
  tweet = BeautifulSoup(tweet, "lxml").get_text() # turns xml-formatted text into regular text
  tweet = re.sub(r"@[A-Za-z0-9]+", " ", tweet) # gets rid of all user references in tweets (i.e. "@username")
  tweet = re.sub(r"https?://[A-Za-z0-9./]+", " ", tweet) # gets rid of URLs
  tweet = re.sub(r"[^A-Za-z.!?áéíóúüñ¿ÁÉÍÓÚÜÑ']", " ", tweet) # gets rid of any non-standard characters in the tweets
  tweet = re.sub(r" +", " ", tweet) # replaces all excess whitespace with a single space

  return tweet # gives us our cleaned tweet

sentiment_tokenizer = XLMRobertaTokenizer.from_pretrained('xlm-roberta-base', do_lower_case=True)

device = torch.device('cpu')

def predict_sentiment(tweet, language):
    
    tweet = clean_tweet(tweet)
    tweet_input_id = []
    tweet_attention_mask = []

    tweet_dict = sentiment_tokenizer.encode_plus(
                            tweet,                      # Sentence to encode.
                            add_special_tokens = True, # Add '[CLS]' and '[SEP]'
                            max_length = 64,           # Pad & truncate all sentences.
                            truncation=True,           # Explicitly enable truncation
                            padding='max_length',
                            return_attention_mask = True,   # Construct attn. masks.
                            return_tensors = 'pt',     # Return pytorch tensors.
                       )

    # Add the encoded sentence to the list.    
    tweet_input_id.append(tweet_dict['input_ids'])

    # And its attention mask (simply differentiates padding from non-padding).
    tweet_attention_mask.append(tweet_dict['attention_mask'])

    # Convert the lists into tensors.
    tweet_input_id = torch.cat(tweet_input_id, dim=0)
    tweet_attention_mask = torch.cat(tweet_attention_mask, dim=0)

    tweet_data = TensorDataset(tweet_input_id, tweet_attention_mask)
    
    tweet_dataloader = DataLoader(tweet_data)
    
    for data in tweet_dataloader:
        tweet_input_id = data[0].to(device)
        tweet_attention_mask = data[1].to(device)
    
    tweet_logits = sentiment_model(tweet_input_id, token_type_ids=None, attention_mask=tweet_attention_mask)
    
    tweet_logits = tweet_logits[0].detach().cpu().numpy()

    tweet_logits = torch.Tensor(tweet_logits)

    softmax = torch.nn.Softmax(dim=1)
    prob_dist = softmax(tweet_logits)

    sentiment_pred = prob_dist.tolist()

    sentiment_pred = sentiment_pred[0][1]

    return sentiment_pred

print(predict_sentiment("This is the best day ever!", "english"))
print(predict_sentiment("Este es el peor dia de mi vida", "spanish"))
print(predict_sentiment("C'est le meilleur jour de ma vie!", "french"))
print(predict_sentiment("Que dia horrível para estar vivo", "portuguese"))
print(predict_sentiment("Vorrei non essere vivo adesso", "italian"))
print(predict_sentiment("Ini adalah hari terburuk yang pernah ada", "indonesian"))
print(predict_sentiment("Co za wspaniały dzień do życia!", "polish"))
print(predict_sentiment("Dies ist ein schrecklicher Tag", "german"))
print(predict_sentiment("我喜欢活着!", "chinese"))
print(predict_sentiment("Bu berbat bir gün", "turkish"))
print(predict_sentiment("काश मैं मर चुका होता", "hindi"))

# language selections: ["fr", "es", "it", "pt", "pt_br", "ro", "ca", "gl", "pt_BR", "la", "wa", "fur", "oc", "fr_CA", "sc", "es_ES", "es_MX", 
# "es_AR", "es_PR", "es_UY", "es_CL", "es_CO", "es_CR", "es_GT", "es_HN", "es_NI", "es_PA", "es_PE", "es_VE", "es_DO", "es_EC", 
# "es_SV", "an", "pt_PT", "frp", "lad", "vec", "fr_FR", "co", "it_IT", "lld", "lij", "lmo", "nap", "rm", "scn", "mwl"]

def TranslateWithSentimentSelection(sentence, num_candidates, language):

  if language == "fr" or "es" or "it" or "pt" or "ro":
    model = romance_model
    tokenizer = romance_tokenizer
  if language == "id":
    model = indonesian_model
    tokenizer = indonesian_tokenizer
  # if language == "pl" or "ru":
  #   model = slavic_model
  #   tokenizer = slavic_tokenizer
  # if language == "de":
  #   model = german_model
  #   tokenizer = german_tokenizer
  # if language == "fi":
  #   model = finnish_model
  #   tokenizer = finnish_tokenizer

  source_sentence = f'>>{language}<< {sentence}'
  translated = model.generate(**tokenizer.prepare_seq2seq_batch([source_sentence]), num_beams=num_candidates, num_return_sequences=num_candidates)
  candidate_translations = [tokenizer.decode(t, skip_special_tokens=True) for t in translated]
  
  source_sentiment = predict_sentiment(sentence, "english")
  target_sentiments = [predict_sentiment(candidate, language) for candidate in candidate_translations]
  sentiment_divergence_list = []
  for i in range(len(target_sentiments)):
    sentiment_divergence_list.append(abs(target_sentiments[i] - source_sentiment))
  translation = candidate_translations[sentiment_divergence_list.index(min(sentiment_divergence_list))]
  
  return translation

def TranslateBaseline(sentence, language):

  if language == "fr" or "es" or "it" or "pt" or "ro":
    model = romance_model
    tokenizer = romance_tokenizer
  if language == "id":
    model = indonesian_model
    tokenizer = indonesian_tokenizer
  # if language == "pl" or "ru":
  #   model = slavic_model
  #   tokenizer = slavic_tokenizer
  # if language == "de":
  #   model = german_model
  #   tokenizer = german_tokenizer
  # if language == "fi":
  #   model = finnish_model
  #   tokenizer = finnish_tokenizer

  source_sentence = f'>>{language}<< {sentence}'
  translated = model.generate(**tokenizer.prepare_seq2seq_batch([source_sentence]))
  translation = ([tokenizer.decode(t, skip_special_tokens=True) for t in translated])[0]

  return translation

# Testing our modified model against the baseline

example_sentence_1 = "Time Warner Road Runner customer support here absolutely blows."
print("English sentence 1:", example_sentence_1)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_1, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_1, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_2 = "Okay, first assessment of the Kindle . . . it fucking rocks!"
print("English sentence 2:", example_sentence_2)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_2, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_2, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_3 = "Could Time Warner Cable suck more?"
print("English sentence 3:", example_sentence_3)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_3, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_3, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_4 = "LeBron is a monsta and he is only 24. SMH The world ain't ready."
print("English sentence 4:", example_sentence_4)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_4, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_4, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_5 = "I know my life has been flipped upside down when I just thought in my head that some Ramen sounds good. "
print("English sentence 5:", example_sentence_5)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_5, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_5, 10, "id"))


print("                                                                                   ")
print("                                                                                   ")
example_sentence_6 = "I'm sorry—I'm feeling kinda yucky myself—5am is going to come too quick."
print("English sentence 6:", example_sentence_6)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_6, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_6, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_7 = "I need a new boyfriend... I'm stuck in a rut"
print("English sentence 7:", example_sentence_7)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_7, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_7, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_8 = "aww that stinks!"
print("English sentence 8:", example_sentence_8)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_8, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_8, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_9 = "I'm tired. I feel like crap. And the world feels all crummy. Make me happy, USB disco mouse. "
print("English sentence 9:", example_sentence_9)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_9, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_9, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_10 = "why are people such wankers these days?"
print("English sentence 10:", example_sentence_10)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_10, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_10, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_11 = "@Holidaybot is rubbish! . . ."
print("English sentence 11:", example_sentence_11)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_11, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_11, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_12 = "@apple Contact sync between Yosemite and iOS8 is seriously screwed up. It used to be much more stable in the past"
print("English sentence 12:", example_sentence_12)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_12, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_12, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_13 = "Can't stand those ppl with @Apple stickers everywhere."
print("English sentence 13:", example_sentence_13)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_13, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_13, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_14 = "As a die hard @Apple customer, I must say I am truly displeased with the customer service I was given today."
print("English sentence 14:", example_sentence_14)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_14, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_14, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_15 = "Just broke my 3rd charger of the month. Get your shit together @apple"
print("English sentence 15:", example_sentence_15)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_15, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_15, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_16 = "Yo @Apple fix your shitty iMessage"
print("English sentence 16:", example_sentence_16)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_16, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_16, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_17 = "@apple please get yourself together! I need my products to work!"
print("English sentence 17:", example_sentence_17)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_17, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_17, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_18 = "@Apple the no caller ID thing is scary as heck and I suggest you stop it"
print("English sentence 18:", example_sentence_18)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_18, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_18, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")
example_sentence_19 = "@Apple tbh annoyed with Apple's shit at the moment"
print("English sentence 19:", example_sentence_19)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_19, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_19, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_20 = "Fair enough. But i have the Kindle2 and I think it's perfect  :)"
print("English sentence 20:", example_sentence_20)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_20, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_20, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_21 = "how can you not love Obama? he makes jokes about himself."
print("English sentence 21:", example_sentence_21)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_21, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_21, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_22 = "Went to see the Star Trek movie last night.  Very satisfying."
print("English sentence 22:", example_sentence_22)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_22, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_22, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_23 = "I hate the dentist....who invented them anyways?"
print("English sentence 23:", example_sentence_23)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_23, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_23, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_24 = "@ Safeway. Place is a nightmare right now. Bumming."
print("English sentence 24:", example_sentence_24)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_24, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_24, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_25 = "Reading the tweets coming out of Iran... The whole thing is terrifying and incredibly sad..."
print("English sentence 25:", example_sentence_25)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_25, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_25, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_26 = "with the boyfriend, eating a quesadilla"
print("English sentence 26:", example_sentence_26)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_26, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_26, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_27 = "Hate safeway select green tea icecream! bought two cartons, what a waste of money. "
print("English sentence 27:", example_sentence_27)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_27, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_27, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_28 = "I am furious with Time Warner and their phone promotions!"
print("English sentence 28:", example_sentence_28)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_28, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_28, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_29 = "is upset about the whole GM thing. life as i know it is so screwed up"
print("English sentence 29:", example_sentence_29)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_29, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_29, 10, "id"))

print("                                                                                   ")
print("                                                                                   ")

example_sentence_30 = "saw night at the museum out of sheer desperation. who is funding these movies?"
print("English sentence 30:", example_sentence_30)
print("-----------------------------------------------------------------------------------")
print("Baseline model translation:", TranslateBaseline(example_sentence_30, "id"))
print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_30, 10, "id"))

# # Testing our modified model against the baseline

# # FRENCH

# example_sentence_1 = "Time Warner Road Runner customer support here absolutely blows."
# print("English sentence 1:", example_sentence_1)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_1, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_1, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_2 = "Okay, first assessment of the Kindle . . . it fucking rocks!"
# print("English sentence 2:", example_sentence_2)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_2, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_2, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_3 = "Could Time Warner Cable suck more?"
# print("English sentence 3:", example_sentence_3)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_3, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_3, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_4 = "is upset about the whole GM thing. life as I know it is so screwed up"
# print("English sentence 4:", example_sentence_4)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_4, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_4, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_5 = "I need a new boyfriend... I'm stuck in a rut."
# print("English sentence 5:", example_sentence_5)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_5, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_5, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_6 = "Yo @Apple fix your shitty iMessage"
# print("English sentence 6:", example_sentence_6)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_6, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_6, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_7 = "why are people such wankers these days?"
# print("English sentence 7:", example_sentence_7)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_7, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_7, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_8 = "As a die hard @Apple customer, I must say I am truly displeased with the customer service I was given today."
# print("English sentence 8:", example_sentence_8)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_8, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_8, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_9 = "I'm sorry—I'm feeling kinda yucky myself—5am is going to come too quick."
# print("English sentence 9:", example_sentence_9)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_9, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_9, 10, "fr"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_10 = "aww that stinks!"
# print("English sentence 10:", example_sentence_10)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_10, "fr"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_10, 10, "fr"))

# # ITALIAN

# example_sentence_1 = "Time Warner Road Runner customer support here absolutely blows."
# print("English sentence 1:", example_sentence_1)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_1, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_1, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_2 = "Okay, first assessment of the Kindle . . . it fucking rocks!"
# print("English sentence 2:", example_sentence_2)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_2, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_2, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_3 = "Could Time Warner Cable suck more?"
# print("English sentence 3:", example_sentence_3)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_3, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_3, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_4 = "is upset about the whole GM thing. life as I know it is so screwed up"
# print("English sentence 4:", example_sentence_4)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_4, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_4, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_5 = "I need a new boyfriend... I'm stuck in a rut."
# print("English sentence 5:", example_sentence_5)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_5, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_5, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_6 = "Yo @Apple fix your shitty iMessage"
# print("English sentence 6:", example_sentence_6)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_6, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_6, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_7 = "why are people such wankers these days?"
# print("English sentence 7:", example_sentence_7)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_7, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_7, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_8 = "As a die hard @Apple customer, I must say I am truly displeased with the customer service I was given today."
# print("English sentence 8:", example_sentence_8)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_8, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_8, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_9 = "I'm sorry—I'm feeling kinda yucky myself—5am is going to come too quick."
# print("English sentence 9:", example_sentence_9)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_9, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_9, 10, "it"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_10 = "aww that stinks!"
# print("English sentence 10:", example_sentence_10)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_10, "it"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_10, 10, "it"))

# # PORTUGUESE

# example_sentence_1 = "Time Warner Road Runner customer support here absolutely blows."
# print("English sentence 1:", example_sentence_1)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_1, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_1, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_2 = "Okay, first assessment of the Kindle . . . it fucking rocks!"
# print("English sentence 2:", example_sentence_2)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_2, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_2, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_3 = "Could Time Warner Cable suck more?"
# print("English sentence 3:", example_sentence_3)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_3, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_3, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_4 = "is upset about the whole GM thing. life as I know it is so screwed up"
# print("English sentence 4:", example_sentence_4)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_4, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_4, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_5 = "I need a new boyfriend... I'm stuck in a rut."
# print("English sentence 5:", example_sentence_5)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_5, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_5, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_6 = "Yo @Apple fix your shitty iMessage"
# print("English sentence 6:", example_sentence_6)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_6, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_6, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_7 = "why are people such wankers these days?"
# print("English sentence 7:", example_sentence_7)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_7, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_7, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_8 = "As a die hard @Apple customer, I must say I am truly displeased with the customer service I was given today."
# print("English sentence 8:", example_sentence_8)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_8, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_8, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_9 = "I'm sorry—I'm feeling kinda yucky myself—5am is going to come too quick."
# print("English sentence 9:", example_sentence_9)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_9, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_9, 10, "pt"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_10 = "aww that stinks!"
# print("English sentence 10:", example_sentence_10)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_10, "pt"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_10, 10, "pt"))

# # CROATIAN

# example_sentence_1 = "Time Warner Road Runner customer support here absolutely blows."
# print("English sentence 1:", example_sentence_1)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_1, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_1, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_2 = "Okay, first assessment of the Kindle . . . it fucking rocks!"
# print("English sentence 2:", example_sentence_2)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_2, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_2, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_3 = "Could Time Warner Cable suck more?"
# print("English sentence 3:", example_sentence_3)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_3, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_3, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_4 = "is upset about the whole GM thing. life as I know it is so screwed up"
# print("English sentence 4:", example_sentence_4)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_4, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_4, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_5 = "I need a new boyfriend... I'm stuck in a rut."
# print("English sentence 5:", example_sentence_5)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_5, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_5, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_6 = "Yo @Apple fix your shitty iMessage"
# print("English sentence 6:", example_sentence_6)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_6, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_6, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_7 = "why are people such wankers these days?"
# print("English sentence 7:", example_sentence_7)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_7, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_7, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_8 = "As a die hard @Apple customer, I must say I am truly displeased with the customer service I was given today."
# print("English sentence 8:", example_sentence_8)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_8, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_8, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_9 = "I'm sorry—I'm feeling kinda yucky myself—5am is going to come too quick."
# print("English sentence 9:", example_sentence_9)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_9, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_9, 10, "pl"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_10 = "aww that stinks!"
# print("English sentence 10:", example_sentence_10)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_10, "pl"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_10, 10, "pl"))

# # GERMAN

# example_sentence_1 = "Time Warner Road Runner customer support here absolutely blows."
# print("English sentence 1:", example_sentence_1)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_1, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_1, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_2 = "Okay, first assessment of the Kindle . . . it fucking rocks!"
# print("English sentence 2:", example_sentence_2)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_2, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_2, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_3 = "Could Time Warner Cable suck more?"
# print("English sentence 3:", example_sentence_3)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_3, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_3, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_4 = "is upset about the whole GM thing. life as I know it is so screwed up"
# print("English sentence 4:", example_sentence_4)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_4, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_4, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_5 = "I need a new boyfriend... I'm stuck in a rut."
# print("English sentence 5:", example_sentence_5)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_5, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_5, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_6 = "Yo @Apple fix your shitty iMessage"
# print("English sentence 6:", example_sentence_6)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_6, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_6, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_7 = "why are people such wankers these days?"
# print("English sentence 7:", example_sentence_7)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_7, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_7, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_8 = "As a die hard @Apple customer, I must say I am truly displeased with the customer service I was given today."
# print("English sentence 8:", example_sentence_8)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_8, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_8, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_9 = "I'm sorry—I'm feeling kinda yucky myself—5am is going to come too quick."
# print("English sentence 9:", example_sentence_9)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_9, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_9, 10, "de"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_10 = "aww that stinks!"
# print("English sentence 10:", example_sentence_10)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_10, "de"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_10, 10, "de"))

# # FINNISH

# example_sentence_1 = "Time Warner Road Runner customer support here absolutely blows."
# print("English sentence 1:", example_sentence_1)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_1, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_1, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_2 = "Okay, first assessment of the Kindle . . . it fucking rocks!"
# print("English sentence 2:", example_sentence_2)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_2, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_2, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_3 = "Could Time Warner Cable suck more?"
# print("English sentence 3:", example_sentence_3)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_3, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_3, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_4 = "is upset about the whole GM thing. life as I know it is so screwed up"
# print("English sentence 4:", example_sentence_4)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_4, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_4, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_5 = "I need a new boyfriend... I'm stuck in a rut."
# print("English sentence 5:", example_sentence_5)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_5, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_5, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_6 = "Yo @Apple fix your shitty iMessage"
# print("English sentence 6:", example_sentence_6)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_6, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_6, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_7 = "why are people such wankers these days?"
# print("English sentence 7:", example_sentence_7)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_7, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_7, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_8 = "As a die hard @Apple customer, I must say I am truly displeased with the customer service I was given today."
# print("English sentence 8:", example_sentence_8)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_8, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_8, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_9 = "I'm sorry—I'm feeling kinda yucky myself—5am is going to come too quick."
# print("English sentence 9:", example_sentence_9)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_9, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_9, 10, "fi"))

# print("                                                                                   ")
# print("                                                                                   ")

# example_sentence_10 = "aww that stinks!"
# print("English sentence 10:", example_sentence_10)
# print("-----------------------------------------------------------------------------------")
# print("Baseline model translation:", TranslateBaseline(example_sentence_10, "fi"))
# print("Modified model translation:", TranslateWithSentimentSelection(example_sentence_10, 10, "fi"))